# MyLDAEnvClassifier.R
# -----------------------------------------------------------------------------
# Author:             Bahman Afsari, Albert Kuo
# Date last modified: Sep 24, 2019
#
# Function for classification and correlation using LDA, logistic, or random forest

library(randomForest)
library(nnls)
library(MASS)
library(dplyr) # Note that you must load dplyr after MASS to preserve select function
library(rsample)
library(here)
source(here("code", "MyCor.R"))


# in$dt is dt_new returned by FeatureSelection
# in$test_ind is the indices for the test data
# in$factor is the factor to be tested (e.g. Age, Smoking)
# in$nmf_out is the output from UnsupervisedSigs
# in$unsupervised_sig is the formula for unsupervised signature from signature_caf
# in$random_out is the column vector generated by the random signature
# in$classifier = any or all of c("LDA", "Logit", "RF", "NNLS")
# in$keep_classifier is a toggle for whether to return the model
# in$calculate_corr is a toggle for whether to calculate the correlations
# in$adjusted_formula is a toggle for whether to use adjusted formula for exposed/unexposed
# in$features_selected is a vector of predictive features (e.g. F2, F5, ...)
# in$select_n is a vector of the best n for each classifier
# out$auc is a vector of AUCs for each classifier
# out$corr is a vector of correlations with a continuous exposure (when applicable)
# out$signature is the signature we generated on the whole set (not NMF or Alexandrov's)
# out$dt is the data we use for prediction (both training and test)
# out$classifier is a list of saved models for each classifier
MyLDAEnvClassifier <- function(dt, test_ind = NULL,
                               factor,
                               nmf_out,
                               unsupervised_sig,
                               random_out,
                               classifier, # Options are "LDA", "Logit", "RF"
                               keep_classifier = F,
                               calculate_corr = T,
                               adjusted_formula = F,
                               features_selected,
                               select_n){
  if(is.null(test_ind)){
    train_ind <- 1:nrow(dt)
    test_ind <- train_ind
  } else {
    train_ind <- setdiff(1:nrow(dt), test_ind)
  }
  
  train <- dt[train_ind, ]
  
  # Do not perform LDA if select_n["LDA"] is missing
  if(is.na(select_n["LDA"])){
    classifier = setdiff(classifier, "LDA")
  }
  
  # Data transformations for unsupervised sigs (if applicable)
  if(factor == "AGE"){
    unsupervised_dt <- dt %>% 
      transmute_(paste("(", unsupervised_sig, ")"))
  } else {
    if(adjusted_formula){
      unsupervised_dt <- dt %>% 
        transmute_(paste("(", unsupervised_sig, ")/TOTAL_MUTATIONS"))
      nmf_out <- nmf_out %>%
        mutate_all(.funs = funs(./dt[test_ind, "TOTAL_MUTATIONS"]))
      random_out$random <- ifelse(is.na(random_out$random), NA,
                                  random_out$random/dt[test_ind, "TOTAL_MUTATIONS"])
      random_out$singlepeak <- ifelse(is.na(random_out$singlepeak), NA,
                                      random_out$singlepeak/dt[test_ind, "TOTAL_MUTATIONS"])
    } else {
      unsupervised_dt <- dt %>% 
        transmute_(paste("(", unsupervised_sig, ")"))
    }
  }
  
  # Compute unsupervised AUCs
  test_indvar <- dt[test_ind, "IndVar"]
  alex_auc <- MyAuc(test_indvar, unsupervised_dt[test_ind, ])
  best_nmf_auc <- MyAuc(test_indvar, nmf_out$best_nmf) 
  matched_nmf_auc <- MyAuc(test_indvar, nmf_out$matched_sig) 
  random_auc <- MyAuc(test_indvar, random_out$random)
  singlepeak_auc <- MyAuc(test_indvar, random_out$singlepeak)
  
  out <- list(auc = c(Alex = alex_auc, 
                      Best_NMF = best_nmf_auc, 
                      Matched_NMF = matched_nmf_auc,
                      Random = random_auc,
                      SinglePeak = singlepeak_auc),
              corr = c(),
              signature = list(),
              classifier = list())
  
  # Compute AUC for when the unsupervised signature for age is fixed to be Signature.1
  if(factor == "AGE"){
    signature1_dt <- dt %>% select("Signature.1")
    signature1_auc <- MyAuc(test_indvar, signature1_dt[test_ind, ])
    out$auc <- c(out$auc, Signature1 = signature1_auc)
  }
  
  # Calculate median rates and transform data
  if(factor == "AGE"){
      # Calculate median rates -> signature
      median_rates <- train %>%
        summarize_at(.vars = features_selected,
                     .funs = funs(median(. , na.rm = T)/median(AGE, na.rm = T)))
  } else {
    # Calculate grouped rates = unexposed and exposed signature
    grouped_rates <- train %>%
      group_by(IndVar) %>%
      summarize_at(.vars = features_selected,
                   .funs = funs(median(.,na.rm=T)/median(AGE,na.rm=T)))
    
    unexposed_rates <- grouped_rates %>% filter(IndVar == F) %>% select(-IndVar)
    exposed_rates <- grouped_rates %>% filter(IndVar == T) %>% select(-IndVar)
    
    # Calculate median rates = difference in rates between exposed and unexposed -> signature
    median_rates <- exposed_rates - unexposed_rates
    
    if(adjusted_formula){
      # Remove unexposed median rate (i.e. aging rate) from training and test data
      remove_age_formula <- colnames(unexposed_rates) %>%
        sapply(FUN = function(x) paste0("`", x, "`", "-AGE*", unexposed_rates[x]))
      
      dt <- dt %>%
        mutate_(.dots = remove_age_formula) %>%
        mutate_at(.vars = features_selected,
                  .funs = funs(./TOTAL_MUTATIONS))
    } else {
      dt <- dt %>%
        mutate_at(.vars = features_selected,
                  .funs = funs(./AGE))
    }
    
    # Remove observations missing age
    missing_ind <- which(is.na(dt$AGE))
    train_ind <- setdiff(train_ind, missing_ind)
    test_ind <- setdiff(test_ind, missing_ind)
    train <- dt[train_ind, ]
    test_indvar <- dt[test_ind, "IndVar"]
  } 
  
  # Classification
  # If no test data or all training data has the same IndVar
  if(length(test_ind) == 0 || length(unique(train$IndVar)) == 1){
    warning("No test data")
    
    # Return NA to AUC
    auc <- sapply(classifier, function(x) NA)
    out$auc <- c(out$auc, auc)
    
    # Return NA to corr
    if(factor %in% c("AGE", "SMOKING")){
      corr <- sapply(classifier, function(x) NA)
      out$corr <- c(out$corr, corr)
    }
  } else {
    # Linear Discriminant Analysis
    if("LDA" %in% classifier){
      if(factor == "AGE"){
        # Take log2 for counts for age for better normal distribution
        # dt <- dt %>%
        #   mutate_at(.vars = features_selected[1:select_n["LDA"]],
        #             .funs = funs(log2(. + 1)))
        
        train <- dt[train_ind, ]
      }
      
      x <- train[, features_selected[1:select_n["LDA"]], drop = F] %>% as.matrix()
      grouping <- train$IndVar
      out$auc <- c(out$auc, LDA = NA)
      lda_prediction <- NA
      lda_rates <- NA
      try({
        lda_classifier <- lda(x, grouping, prior = c(0.5, 0.5))
        newdata <- dt[test_ind, features_selected[1:select_n["LDA"]], drop = F] %>% as.matrix()
        lda_prediction <- predict(lda_classifier, newdata = newdata)$x
        
        out$auc["LDA"] = MyAuc(test_indvar, lda_prediction)
        if(keep_classifier) 
          out$classifier$LDA <- lda_classifier
        
        # Calculate mean difference in rates or counts
        lda_rates <- lda_classifier$means %>% as.data.frame()
        lda_rates <- lda_rates %>% mutate(IndVar = as.logical(rownames(lda_rates)))
        unexposed_lda_rates <- lda_rates %>% filter(IndVar == F) %>% select(-IndVar)
        exposed_lda_rates <- lda_rates %>% filter(IndVar == T) %>% select(-IndVar)
        lda_rates <- exposed_lda_rates - unexposed_lda_rates
      })
    }
    
    # Random Forest
    if("RF" %in% classifier){
      x <- train[, features_selected[1:select_n["RF"]], drop = F] %>% as.matrix()
      y_factor <- as.factor(train$IndVar)
      out$auc <- c(out$auc, RF = NA)
      rf_prediction <- NA
      try({
        rf_classifier <- randomForest(x, y = y_factor,
                                      mtry = min(ncol(x), round(log2(ncol(dt)))),
                                      maxnodes = 2, classwt = c(0.5, 0.5))
        
        newdata <- dt[test_ind, features_selected[1:select_n["RF"]], drop = F] %>% as.matrix()
        rf_prediction <- predict(rf_classifier, newdata = newdata,
                                 type = "prob")[, levels(y_factor)[2]]
        
        out$auc["RF"] <- MyAuc(test_indvar, rf_prediction)
        if(keep_classifier) 
          out$classifier$RF <- rf_classifier
      })
    }
    
    # Logistic Regression
    if("Logit" %in% classifier){
      z <- dt %>%
        select(c(features_selected[1:select_n["Logit"]], "IndVar")) %>%
        rename_at(vars(features_selected[1:select_n["Logit"]]), function(x) paste0("X", 1:length(features_selected[1:select_n["Logit"]])))
      
      x <- z[train_ind, ]
      newdata <- z[test_ind, ]
      out$auc <- c(out$auc, Logit = NA)
      logit_prediction <- NA
      try({
        logit_classifier <- glm(formula = IndVar ~ ., data = x, family = binomial())
        logit_prediction <- predict(logit_classifier, newdata = newdata, type = "response")
        logit_betas <- coef(logit_classifier) # beta vector
        logit_betas <- coef(logit_classifier)[-1] # beta vector except beta_0
        
        # Calculate empirical mean differences
        if(factor == "AGE"){
          grouped_rates <- dt %>%
            slice(train_ind) %>%
            group_by(IndVar) %>%
            summarize_at(.vars = features_selected[1:select_n["Logit"]],
                         .funs = funs(mean(., na.rm = T)))
        } else {
          grouped_rates <- dt %>%
            slice(train_ind) %>%
            group_by(IndVar) %>%
            summarize_at(.vars = features_selected[1:select_n["Logit"]],
                         .funs = funs(mean(./AGE, na.rm = T)))
        }
        
        unexposed_rates <- grouped_rates %>% filter(IndVar == F) %>% select(-IndVar)
        exposed_rates <- grouped_rates %>% filter(IndVar == T) %>% select(-IndVar)
        
        # Calculate mean_diff = difference in counts or rates between exposed and unexposed -> signature representation
        mean_diffs <- exposed_rates - unexposed_rates
        
        # Save signature (empirical mean rates and beta coefficients) and select_n for apparent
        if(identical(test_ind, train_ind)){
          # Logit beta coefficients
          names(logit_betas) <- features_selected[1:select_n["Logit"]]
          names(mean_diffs) <- features_selected[1:select_n["Logit"]]
          
          out$signature <- list(mean_diffs = mean_diffs, logit_betas = logit_betas, select_n = select_n)
        }
        
        out$auc["Logit"] = MyAuc(test_indvar, logit_prediction)
        if(keep_classifier) 
          out$classifier$Logit <- logit_classifier
      })
    }
    
    # NNLS
    if("NNLS_Logit_means" %in% classifier && "Logit" %in% classifier){
      newdata <- dt[test_ind, features_selected[1:select_n["Logit"]], drop = F]
      out$auc <- c(out$auc, "NNLS_Logit_means" = NA)
      nnls_coeffs <- NA
      try({
        nnls_coeffs <- newdata %>%
          apply(MARGIN = 1, FUN = function(y)
            nnls(matrix(as.numeric(mean_diffs), ncol = 1),
                 matrix(y, ncol = 1))$x)
        out$auc["NNLS_Logit_means"] <- MyAuc(test_indvar, nnls_coeffs)
        if(keep_classifier)
          out$classifier$NNLS_Logit_means <- mean_diffs
      })
    }
    
    if("NNLS_Logit_betas" %in% classifier && "Logit" %in% classifier){
      newdata <- dt[test_ind, features_selected[1:select_n["Logit"]], drop = F]
      out$auc <- c(out$auc, "NNLS_Logit_betas" = NA)
      nnls_betas_coeffs <- NA
      try({
        nnls_betas_coeffs <- newdata %>%
          apply(MARGIN = 1, FUN = function(y)
            nnls(matrix(as.numeric(logit_betas), ncol = 1),
                 matrix(y, ncol = 1))$x)
        out$auc["NNLS_Logit_betas"] <- MyAuc(test_indvar, nnls_betas_coeffs)
        if(keep_classifier)
          out$classifier$NNLS_Logit_betas <- logit_betas
      })
    }
    
    # Correlation
    if(calculate_corr){
      if(factor == "AGE"){
        continuous_factor = dt[test_ind, "AGE"]
        # Unsupervised correlations
        out$corr <- c(out$corr, Alex = MyCor(x = unsupervised_dt[test_ind, ] + 1e-8,
                                             y = continuous_factor, 
                                             method = "spearman", use = "na.or.complete"))
        out$corr <- c(out$corr, Best_NMF = MyCor(x = nmf_out$best_nmf + 1e-8,
                                                 y = continuous_factor, 
                                                 method = "spearman", use = "na.or.complete"))
        out$corr <- c(out$corr, Matched_NMF = MyCor(x = nmf_out$matched_sig + 1e-8,
                                                    y = continuous_factor, 
                                                    method = "spearman", use = "na.or.complete"))
        # Supervised correlations
        if("LDA" %in% classifier){
          out$corr <- c(out$corr, LDA = MyCor(x = lda_prediction, 
                                              y = continuous_factor, 
                                              method = "spearman", use = "na.or.complete"))
        }
        if("RF" %in% classifier){
          out$corr <- c(out$corr, RF = MyCor(x = rf_prediction, 
                                             y = continuous_factor, 
                                             method = "spearman", use = "na.or.complete"))
        }
        if("Logit" %in% classifier){
          out$corr <- c(out$corr, Logit = MyCor(x = logit_prediction, 
                                                y = continuous_factor, 
                                                method = "spearman", use = "na.or.complete")) 
        }
        if("NNLS_Logit_means" %in% classifier){
          out$corr <- c(out$corr, "NNLS_Logit_means" = MyCor(x = nnls_coeffs, 
                                               y = continuous_factor, 
                                               method = "spearman", use = "na.or.complete"))
        }
        if("NNLS_Logit_betas" %in% classifier){
          out$corr <- c(out$corr, "NNLS_Logit_betas" = MyCor(x = nnls_betas_coeffs, 
                                                             y = continuous_factor, 
                                                             method = "spearman", use = "na.or.complete"))
        }
      } else if(factor == "SMOKING"){
        continuous_factor = dt[test_ind, "SMOKING_PACKS"]/dt[test_ind, "AGE"]
        total_mutations = dt[test_ind, "TOTAL_MUTATIONS"]
        # Unsupervised correlations
        out$corr <- c(out$corr, Alex = MyCor(x = unsupervised_dt[test_ind,]*total_mutations/(total_mutations - unsupervised_dt[test_ind,]), # Why this formula?
                                             y = continuous_factor, 
                                             method = "spearman", use = "na.or.complete"))
        out$corr <- c(out$corr, Best_NMF = MyCor(x = (nmf_out$best_nmf[test_ind] + 1e-8)/(nmf_out$age_nmf[test_ind] + 1e-8),
                                                 y = continuous_factor, 
                                                 method = "spearman", use = "na.or.complete"))
        out$corr <- c(out$corr, Matched_NMF = MyCor(x = (nmf_out$matched_sig[test_ind] + 1e-8)/(nmf_out$matched_age_sig[test_ind] + 1e-8), # To not divide by 0?
                                                    y = continuous_factor, 
                                                    method = "spearman", use = "na.or.complete"))
        # Supervised correlations
        if("LDA" %in% classifier){
          out$corr <- c(out$corr, LDA = MyCor(x = lda_prediction, 
                                              y = continuous_factor, 
                                              method = "spearman", use = "na.or.complete"))
        }
        if("RF" %in% classifier){
          out$corr <- c(out$corr, RF = MyCor(x = rf_prediction, 
                                             y = continuous_factor, 
                                             method = "spearman", use = "na.or.complete"))
        }
        if("Logit" %in% classifier){
          out$corr <- c(out$corr, Logit = MyCor(x = logit_prediction, 
                                                y = continuous_factor, 
                                                method = "spearman", use = "na.or.complete"))
        }
        if("NNLS_Logit_means" %in% classifier){
          out$corr <- c(out$corr, "NNLS_Logit_means" = MyCor(x = nnls_coeffs/(total_mutations - nnls_coeffs), # Why this formula?
                                               y = continuous_factor, 
                                               method = "spearman", use = "na.or.complete"))
        }
        if("NNLS_Logit_betas" %in% classifier){
          out$corr <- c(out$corr, "NNLS_Logit_betas" = MyCor(x = nnls_betas_coeffs/(total_mutations - nnls_betas_coeffs), # Why this formula?
                                                             y = continuous_factor, 
                                                             method = "spearman", use = "na.or.complete"))
        }
      }
    }
  }
  
  return(out)
}


# No data dependencies

# Test function
# signature_caf <- readRDS(here("data", "signature_caf.rds"))
# factor <- "AGE"
# tissue <- "LUAD"
# ind <- which((signature_caf["Factor",] == factor) & (signature_caf["Tissue",] == tissue))
# dt <- signature_caf[["Data", ind]]$DataSetFiltered %>%
#   filter(TOTAL_MUTATIONS > 0)
# unsupervised_sig = signature_caf[["Unsupervised", ind]]
# age_ind <- which((signature_caf["Factor",] == "AGE") & (signature_caf["Tissue",] == tissue))
# age_sig <- signature_caf[["Unsupervised", age_ind]]
# 
# source(here("code", "UnsupervisedSigs.R"))
# nmf_out <- UnsupervisedSigs(dt = dt,
#                  test_ind = NULL,
#                  unsupervised_sig = unsupervised_sig,
#                  age_sig = age_sig)
# 
# source(here("code", "RandomSigs.R"))
# random_out <- RandomSigs(dt = dt,
#                       test_ind = NULL,
#                       factor = factor)
# 
# source(here("code", "FeatureSelection.R"))
# features_out = FeatureSelection(dt = dt, middle_dt = NULL,
#                                 nmf_out = nmf_out,
#                                 random_out = random_out,
#                                 unsupervised_sig = unsupervised_sig,
#                                 factor = factor)
# dt = features_out$dt_new
# classifier = c("LDA", "Logit", "RF", "NNLS")
# keep_classifier = F
# features_selected = features_out$features_selected
# select_n = features_out$select_n
# test_ind = NULL
# 
# test_out = MyLDAEnvClassifier(dt = dt, test_ind = NULL,
#                               factor = factor,
#                               classifier = c("LDA", "Logit", "RF", "NNLS"),
#                               nmf_out = nmf_out,
#                               unsupervised_sig = unsupervised_sig,
#                               random_out = random_out,
#                               keep_classifier = F,
#                               features_selected = features_selected,
#                               select_n = select_n)

# Create test objects for Shiny app
# test_model = MyLDAEnvClassifier(dt = dt, test_ind = NULL,
#                                 factor = factor,
#                                 classifier = c("LDA"),
#                                 keep_classifier = T,
#                                 unsupervised_sig = unsupervised_sig,
#                                 features_selected = features_selected)$classifier
# test_formula = features_out$features_gmsa$new_partition_formula[features_selected]
# saveRDS(list(model = test_model, formula = test_formula), "app/data/test_shiny.rds")
# write.csv(signature_caf[["Data", ind]]$DataSetFiltered[1, ], "app/data/dt.csv", row.names = F)